<?php
return array(
    /*
     * Application ID generated by AppStore
     */
    'appId' => 'ca4546becd26bded28eb0df43a87da88',

    /*
     * Secret generated by AppStore
     */
    'appSecret' => '434ff48f8199cfdea1074a64370fc1a06539da89',

    /*
     * AppStore Secret generated by AppStore
     */
    'appstoreSecret' => '6aea33b8fb8ce830d2bec7bce3cb3b66c1115b68',

    /*
     * Application webhook secret
     */
    'webhookSecretKey' => '123456',

    /*
     * Application old webhook secret
     */
    'webhookSecretKeyOld' => '',

    'db' => array(
        /*
         * PDO DSN
         */
        'connection' => 'mysql:host=localhost;dbname=27528334_db;port=3306',

        /*
         * PDO Database username
         */
        'user' => '27528334_db',

        /*
         * PDO Database password
         */
        'pass' => 'trudnehaslo'
    ),

    /*
     * Enable debug mode or not
     */
    'debug' => true,

    /*
     * Path to log file or empty to disable logging
     */
    'logFile' => "logs/application.log",


    /*
     * timezone of the application
     *
     * Value is passed to date_default_timezone_set function
     */
    'timezone' => 'Europe/Warsaw',

    'php' => array(
        /*
         * This determines whether errors should be printed to the screen as
         * part of the output or if they should be hidden from the user
         *
         * Value is passed to ini_set function
         */
        'display_errors' => 'on'
    )
);
